name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dalexi3/dtgcp:$(date +%s)
    - name: Tag Latest
      run: docker build . --file Dockerfile --tag dalexi3/dtgcp:latest
